system:
  image_to_image: True #有图生图需求请一定要设定为True

comfy:
  url_header: "http"            #协议类型 http or https
  server_domain: "127.0.0.1:8188"   #你的comfy服务器,ip:端口,例子: 10.10.10.10:5000
  default_workflow: "test"       #默认使用的工作流

#  --- 文生图消息 ---
messages:
  start_message: " 正在开始画图"
  complete_message:
    base_string: " 图片完成 "   #这个必须设定
    addtion:                     #从这里开始下面都是可选，按照 属性: "输出内容" 添加，属性值会放到内容后面，会自动添加换行 
      prompt: "提示词: "           
      cfg: "cfg: "
      model: "模型: "
  # --- 图生视频消息 ---
  video_start_message: " 正在制作视频，耗时约为10-15分钟，请耐心等待 "
  video_complete_message:
    base_string: " 视频制作完成 "
    video_addtion:
      positive_prompt: "视频提示词: "
      lora: "LoRA风格: "      

#现在仅作为后缀名的取得，不写就会全部默认是safetensors
comfy_models:                         
  - name: "oneObsession_13"           #模型名字
    type: "safetensors"               #后缀名
      
#机器人传入参数的设定，可以根据自己的需求更改。type的类型只能是int,float,str,bool
#强烈建议设定初始值，AI有时候会丢值，不设定可能导致问题
#因为python的规则，从设置了default值开始的参数，下面都必须设置default，搞不懂就全部设置default
parameters: 
  - name: "prompt"
    type: "str"
    description: "需要把用户的需求翻译成danbooru的tag形式，要选用danbooru.donmai.us里存在的tag，作为输入参数。需要注意，tag不需要带下划线，并且需要保留\\符号"
  - name: "model"
    type: "str"
    description: "默认为oneObsession_13，如果用户指明了模型名，就在oneObsession_13,IL One obsession_MatureEPSv3-A,catTowerNoobaiXL_v17Vpred中选择最接近的。"
    default: "oneObsession_13"
  - name: "width"
    type: "int"
    description: "根据图片需求设定合适的宽度，范围是768-1536, 用户可以自定义。"
    default: 1024
  - name: "height"
    type: "int"
    description: "根据图片需求设定合适的高度，范围是768-1536, 用户可以自定义。"
    default: 1024
  - name: "cfg"
    type: "float"
    description: "默认为5,以0.5为单位，用户可以自定义。"
    default: 5
# --- 新增的图生视频参数 ---
  - name: "task_type"
    type: "str"
    description: "指定任务类型。如果用户明确要求'图生视频'，LLM应将此值设为'video'。"
    default: "image" # 默认任务类型是文生图
  - name: "positive_prompt"
    type: "str"
    description: "【仅当task_type为'video'时使用】用于图生视频的动态效果提示词，可使用中文。"
    default: "大摆锤"
  - name: "lora"
    type: "str"
    description: "【仅当task_type为'video'时使用】选择一个视频动态风格的LoRA。必须从以下列表中选择一个精确的文件名：'dbc.safetensors', 'ruyao.safetensors',如果未指定，则使用默认的'dbc.safetensors'。"
    default: "dbc.safetensors"
switch_workflow:
  # 规则：当 task_type 参数的值等于 "video" 时，切换到 img2video 工作流
  - workflow_name: "img2video"
    param_rule: "task_type,video"