comfy:
  url_header: "http"                    #协议类型 http or https
  server_domain: "10.10.10.10:5000"   #你的comfy服务器,ip:端口
  default_workflow: "test"              #默认使用的工作流

# 设定画图开始和完成发送的消息，可修改内容。
messages:
  start_message: " 努力画图中喵ing♡~~~ "
  complete_message:
    base_string: " 图片好了喵 "   #这个必须设定
    addtion:                     #从这里开始下面都是可选，按照 属性: "输出内容" 添加，属性值会放到内容后面，会自动添加换行 
      prompt: "提示词: "           
      cfg: "cfg: "
      model: "模型: "

#现在仅作为后缀名的取得，不写就会全部默认是safetensors
comfy_models:                         
  - name: "oneObsession_13"           #模型名字
    type: "safetensors"               #后缀名
  - name: "IL One obsession_MatureEPSv3-A"
    type: "safetensors"
      
#机器人传入参数的设定，可以根据自己的需求更改。type的类型只能是int,float,str,bool
#强烈建议设定初始值，AI有时候会丢值，不设定可能导致问题
parameters: 
  - name: "model"
    type: "str"
    description: "默认为oneObsession_13，如果用户指明了模型名，就在oneObsession_13,IL One obsession_MatureEPSv3-A,catTowerNoobaiXL_v17Vpred中选择最接近的。"
    default: "oneObsession_13"
  - name: "prompt"
    type: "str"
    description: "需要把用户的需求翻译成danbooru的tag形式，要选用danbooru.donmai.us里存在的tag，作为输入参数。需要注意，tag不需要带下划线，并且需要保留\\符号"
  - name: "width"
    type: "int"
    description: "根据图片需求设定合适的宽度，范围是768-1536, 用户可以自定义。"
    default: 1024
  - name: "height"
    type: "int"
    description: "根据图片需求设定合适的高度，范围是768-1536, 用户可以自定义。"
    default: 1024
  - name: "cfg"
    type: "float"
    description: "默认为5,以0.5为单位，用户可以自定义。"
    default: 5
  - name: "isHires"
    type: "bool"
    description: "默认为False,只有当用户明确表达需要高清的时候才能设定为True"
    default: False
  - name: "type"
    type: "int"
    description: "默认为1,根据用户的需求，按照['默认':1,'修脸':2]进行设定"
    default: 1

#如果你有多个工作流，就必须在这里设定切换规则，目前只支持模型和参数设定规则。
#判断逻辑是从上到下，满足匹配条件就会停止，所以请注意设定顺序！
switch_workflow:
  - workflow_name: "test_vpred"
    model: "catTowerNoobaiXL_v17Vpred"  #多个模型用逗号隔开
  - workflow_name: "test_hires"
    param_rule: "isHires"           #当把参数作为条件的时候，只写参数名，当参数为True或者有值时会切换工作流。写"参数名,值"，会判断当参数等于值的时切换
  - workflow_name: "test_hires_ad"  #这是模型和参数一起写的例子，会同时满足才会切换。值的内部可以用||(或)和&&(且)以及括号进行逻辑连接，别写其他的！
    model: "oneObsession_13,IL One obsession_MatureEPSv3-A"  #多个模型的例子
    param_rule: "type,2&&isHires"
    